# Generated by Django 5.2 on 2025-05-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('blogs_per_month', models.CharField(max_length=100)),
                ('can_turn_subscribers', models.BooleanField(default=False)),
                ('can_add_paywalls', models.BooleanField(default=False)),
                ('can_setup_schedules', models.BooleanField(default=False)),
            ],
        ),
    ]
